# Usar Python 3.10 oficial como base
FROM python:3.10-slim

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos para o container
COPY . /app

# Atualiza pip
RUN python -m pip install --upgrade pip

# Instala as dependências
RUN pip install -r requirements.txt

# Expõe a porta 5000 (usada pelo Flask)
EXPOSE 5000

# Comando para iniciar a API
CMD ["python", "app.py"]
